version: "3.9"  # optional since v1.27.0
services:
  web-services:
    build: ./SDG-Backend
    restart: unless-stopped
    ports:
      - "5000:5000"
  front-end:
    build: ./SDG-Frontend
    ports:
      - "80:80"
    restart: unless-stopped
