version: "3.9"  # optional since v1.27.0
services:
  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./SDG-Frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    restart: unless-stopped
  web-services:
    build: ./SDG-Backend
    restart: unless-stopped